memory.flash = 'r-xp 0x00000000-0x000fffff'
memory.ram   = 'rwx- 0x20000000-0x2003ffff'
stack = 0x800
heap = 0x800

runtime = 'armv7m_sys'
output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk = 'Makefile'

define.NRF52840_XXAA=1
define.NRFX_UARTE_ENABLED=1
define.NRFX_UARTE0_ENABLED=1
srcs = [
    '.',
    'nrfx/drivers/src',
]
incs = [
    '.',
    'nrfx',
    'cmsis',
    'nrfx/drivers/include',
    'nrfx/mdk',
    'nrfx/templates'
]

export.__box_write = 'fn(i32, const u8*, usize) -> errsize'
export.__box_box1_open.alias = '__box_open'
export.__box_box1_open.type = 'fn(mut i32 *fd, const i8 *path, u32 flags) -> err'
export.__box_box1_close.alias = '__box_close'
export.__box_box1_close.type = 'fn(i32 fd) -> err'
export.__box_box1_read.alias = '__box_read'
export.__box_box1_read.type = 'fn(i32 fd, mut u8 *buffer, usize size) -> errsize'
export.__box_box1_seek.alias = '__box_seek'
export.__box_box1_seek.type = 'fn(i32 fd, usize off, u32 whence) -> errsize'
export.__box_box2_open.alias = '__box_open'
export.__box_box2_open.type = 'fn(mut i32 *fd, const i8 *path, u32 flags) -> err'
export.__box_box2_close.alias = '__box_close'
export.__box_box2_close.type = 'fn(i32 fd) -> err'
export.__box_box2_read.alias = '__box_read'
export.__box_box2_read.type = 'fn(i32 fd, mut u8 *buffer, usize size) -> errsize'
export.__box_box2_seek.alias = '__box_seek'
export.__box_box2_seek.type = 'fn(i32 fd, usize off, u32 whence) -> errsize'
export.__box_box3_open.alias = '__box_open'
export.__box_box3_open.type = 'fn(mut i32 *fd, const i8 *path, u32 flags) -> err'
export.__box_box3_close.alias = '__box_close'
export.__box_box3_close.type = 'fn(i32 fd) -> err'
export.__box_box3_read.alias = '__box_read'
export.__box_box3_read.type = 'fn(i32 fd, mut u8 *buffer, usize size) -> errsize'
export.__box_box3_seek.alias = '__box_seek'
export.__box_box3_seek.type = 'fn(i32 fd, usize off, u32 whence) -> errsize'

import.box1_add2  = 'fn(i32, i32) -> err32'
import.box1_hello = 'fn() -> err'
import.box2_add2  = 'fn(i32, i32) -> err32'
import.box2_hello = 'fn() -> err'
import.box3_add2  = 'fn(i32, i32) -> err32'
import.box3_hello = 'fn() -> err'

[box.box1]
runtime = 'armv7m_mpu'
loader.select = 'fs'
loader.fs.path = 'box1.bin'
memory.flash = 'r--p 8192 bytes'
memory.ram   = 'rwx- 0x2003e000-0x2003ffff 8192 bytes'
stack = 0x800
heap = 0x800
idempotent = true

output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk = 'Makefile'

export.box1_add2= 'fn(i32, i32) -> err32'
export.box1_hello = 'fn() -> err'

[box.box2]
runtime = 'armv7m_mpu'
loader.select = 'fs'
loader.fs.path = 'box2.bin'
memory.flash = 'r--p 8192 bytes'
memory.ram   = 'rwx- 0x2003e000-0x2003ffff 8192 bytes'
stack = 0x800
heap = 0x800
idempotent = true

output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk = 'Makefile'

export.box2_add2= 'fn(i32, i32) -> err32'
export.box2_hello = 'fn() -> err'

[box.box3]
runtime = 'armv7m_mpu'
loader.select = 'fs'
loader.fs.path = 'box3.bin'
memory.flash = 'r--p 8192 bytes'
memory.ram   = 'rwx- 0x2003e000-0x2003ffff 8192 bytes'
stack = 0x800
heap = 0x800
idempotent = true

output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk = 'Makefile'

export.box3_add2= 'fn(i32, i32) -> err32'
export.box3_hello = 'fn() -> err'

