////// AUTOGENERATED //////
#include "assert.h"
#include "wasm_export.h"
#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdio.h>
#include <string.h>
#include <sys/types.h>

//// box imports ////

int lfsbox_file_close(int32_t fd);

int32_t lfsbox_file_open(const char *path, uint32_t flags);

ssize_t lfsbox_file_read(int32_t fd, void *buffer, size_t size);

int32_t lfsbox_file_seek(int32_t fd, int32_t off, uint32_t whence);

ssize_t lfsbox_file_write(int32_t fd, const void *buffer, size_t size);

int lfsbox_format(void);

int lfsbox_mount(void);

int lfsbox_rename(const char *oldpath, const char *newpath);

int lfsbox_unmount(void);

//// box exports ////

extern void POWER_CLOCK_IRQHandler(void);

extern void TIMER0_IRQHandler(void);

extern ssize_t __box_write(int32_t a0, const void *a1, size_t size);

extern uint32_t bd_block_count(void);

extern uint32_t bd_block_size(void);

extern int bd_erase(uint32_t block);

extern int bd_prog(uint32_t block, uint32_t off, const void *buffer, size_t size);

extern int bd_read(uint32_t block, uint32_t off, void *buffer, size_t size);

extern int bd_sync(void);

//// box hooks ////

// Initialize box lfsbox. Resets the box to its initial state if already
// initialized.
int __box_lfsbox_init(void);

// Mark the box lfsbox as needing to be reinitialized.
int __box_lfsbox_clobber(void);

// Allocate size bytes on the box's data stack. May return NULL if a stack
// overflow would occur.
void *__box_lfsbox_push(size_t size);

// Deallocate size bytes on the box's data stack.
void __box_lfsbox_pop(size_t size);

// May be called by well-behaved code to terminate the box if execution can
// not continue. Notably used for asserts. Note that __box_abort may be
// skipped if the box is killed because of an illegal operation. Must not
// return.
__attribute__((noreturn))
void __box_abort(int err);

// Provides a minimal implementation of stdout to the box. The exact behavior
// depends on the superbox's implementation of __box_write. If none is
// provided, __box_write links but does nothing.
ssize_t __box_write(int32_t fd, const void *buffer, size_t size);

// Provides a minimal implementation of stdout to the box. The exact behavior
// depends on the superbox's implementation of __box_flush. If none is
// provided, __box_flush links but does nothing.
int __box_flush(int32_t fd);

//// box error codes ////
enum box_errors {
    EOK              = 0,    // No error
    EGENERAL         = 1,    // General error
    ENOENT           = 2,    // No such file or directory
    ESRCH            = 3,    // No such process
    EINTR            = 4,    // Interrupted system call
    EIO              = 5,    // I/O error
    ENXIO            = 6,    // No such device or address
    E2BIG            = 7,    // Argument list too long
    ENOEXEC          = 8,    // Exec format error
    EBADF            = 9,    // Bad file number
    ECHILD           = 10,   // No child processes
    EAGAIN           = 11,   // Try again
    ENOMEM           = 12,   // Out of memory
    EACCES           = 13,   // Permission denied
    EFAULT           = 14,   // Bad address
    EBUSY            = 16,   // Device or resource busy
    EEXIST           = 17,   // File exists
    EXDEV            = 18,   // Cross-device link
    ENODEV           = 19,   // No such device
    ENOTDIR          = 20,   // Not a directory
    EISDIR           = 21,   // Is a directory
    EINVAL           = 22,   // Invalid argument
    ENFILE           = 23,   // File table overflow
    EMFILE           = 24,   // Too many open files
    ENOTTY           = 25,   // Not a typewriter
    ETXTBSY          = 26,   // Text file busy
    EFBIG            = 27,   // File too large
    ENOSPC           = 28,   // No space left on device
    ESPIPE           = 29,   // Illegal seek
    EROFS            = 30,   // Read-only file system
    EMLINK           = 31,   // Too many links
    EPIPE            = 32,   // Broken pipe
    EDOM             = 33,   // Math argument out of domain of func
    ERANGE           = 34,   // Math result not representable
    EDEADLK          = 35,   // Resource deadlock would occur
    ENAMETOOLONG     = 36,   // File name too long
    ENOLCK           = 37,   // No record locks available
    ENOSYS           = 38,   // Function not implemented
    ENOTEMPTY        = 39,   // Directory not empty
    ELOOP            = 40,   // Too many symbolic links encountered
    ENOMSG           = 42,   // No message of desired type
    EIDRM            = 43,   // Identifier removed
    ENOSTR           = 60,   // Device not a stream
    ENODATA          = 61,   // No data available
    ETIME            = 62,   // Timer expired
    ENOSR            = 63,   // Out of streams resources
    ENOLINK          = 67,   // Link has been severed
    EPROTO           = 71,   // Protocol error
    EMULTIHOP        = 72,   // Multihop attempted
    EBADMSG          = 74,   // Not a data message
    EOVERFLOW        = 75,   // Value too large for defined data type
    EILSEQ           = 84,   // Illegal byte sequence
    ENOTSOCK         = 88,   // Socket operation on non-socket
    EDESTADDRREQ     = 89,   // Destination address required
    EMSGSIZE         = 90,   // Message too long
    EPROTOTYPE       = 91,   // Protocol wrong type for socket
    ENOPROTOOPT      = 92,   // Protocol not available
    EPROTONOSUPPORT  = 93,   // Protocol not supported
    EOPNOTSUPP       = 95,   // Operation not supported on transport endpoint
    EAFNOSUPPORT     = 97,   // Address family not supported by protocol
    EADDRINUSE       = 98,   // Address already in use
    EADDRNOTAVAIL    = 99,   // Cannot assign requested address
    ENETDOWN         = 100,  // Network is down
    ENETUNREACH      = 101,  // Network is unreachable
    ENETRESET        = 102,  // Network dropped connection because of reset
    ECONNABORTED     = 103,  // Software caused connection abort
    ECONNRESET       = 104,  // Connection reset by peer
    ENOBUFS          = 105,  // No buffer space available
    EISCONN          = 106,  // Transport endpoint is already connected
    ENOTCONN         = 107,  // Transport endpoint is not connected
    ETIMEDOUT        = 110,  // Connection timed out
    ECONNREFUSED     = 111,  // Connection refused
    EHOSTUNREACH     = 113,  // No route to host
    EALREADY         = 114,  // Operation already in progress
    EINPROGRESS      = 115,  // Operation now in progress
    ESTALE           = 116,  // Stale NFS file handle
    EDQUOT           = 122,  // Quota exceeded
    ECANCELED        = 125,  // Operation Canceled
    EOWNERDEAD       = 130,  // Owner died
    ENOTRECOVERABLE  = 131,  // State not recoverable
};

// wamr shares runtime state, this means imports are shared which
// can cause problems
//
// TODO enforce independent imports...
bool __box_wamr_runtime_initialized = false;

#if defined(__GNUC__)
// state of brk
static uint8_t *__heap_brk = NULL;
// assigned by linker
extern uint8_t __heap_start;
extern uint8_t __heap_end;

// GCC's _sbrk uses sp for bounds checking, this
// does not work if our stack is located before the heap
void *_sbrk(ptrdiff_t diff) {
    if (!__heap_brk) {
        __heap_brk = &__heap_start;
    }

    uint8_t *pbrk = __heap_brk;
    if (pbrk + diff > &__heap_end) {
        return (void*)-1;
    }

    __heap_brk = pbrk+diff;
    return pbrk;
}
#endif

//// __box_abort glue ////

__attribute__((noreturn))
void __box_abort(int err) {
    // if there's no other course of action, we spin
    while (1) {}
}

__attribute__((used))
__attribute__((noreturn))
void __wrap_abort(void) {
    __box_abort(-1);
}

__attribute__((used))
void __wrap_exit(int code) {
    __box_abort(code > 0 ? -code : code);
}

#if defined(__GNUC__)
__attribute__((noreturn))
void __assert_func(const char *file, int line,
        const char *func, const char *expr) {
    printf("%s:%d: assertion \"%s\" failed\n", file, line, expr);
    __box_abort(-1);
}

__attribute__((noreturn))
void _exit(int code) {
    __box_abort(code > 0 ? -code : code);
}
#endif

//// __box_write glue ////

int __box_flush(int32_t fd) {
    return 0;
}

ssize_t __box_cbprintf(
        ssize_t (*write)(void *ctx, const void *buf, size_t size), void *ctx,
        const char *format, va_list args) {
    const char *p = format;
    ssize_t res = 0;
    while (true) {
        // first consume everything until a '%'
        size_t skip = strcspn(p, "%");
        if (skip > 0) {
            ssize_t nres = write(ctx, p, skip);
            if (nres < 0) {
                return nres;
            }
            res += nres;
        }

        p += skip;

        // hit end of string?
        if (!*p) {
            return res;
        }

        // format parser
        bool zero_justify = false;
        bool left_justify = false;
        bool precision_mode = false;
        size_t width = 0;
        size_t precision = 0;

        char mode = 'c';
        uint32_t value = 0;
        size_t size = 0;

        for (;; p++) {
            if (p[1] >= '0' && p[1] <= '9') {
                // precision/width
                if (precision_mode) {
                    precision = precision*10 + (p[1]-'0');
                } else if (p[1] > '0' || width > 0) {
                    width = width*10 + (p[1]-'0');
                } else {
                    zero_justify = true;
                }

            } else if (p[1] == '*') {
                // dynamic precision/width
                if (precision_mode) {
                    precision = va_arg(args, size_t);
                } else {
                    width = va_arg(args, size_t);
                }

            } else if (p[1] == '.') {
                // switch mode
                precision_mode = true;

            } else if (p[1] == '-') {
                // left-justify
                left_justify = true;

            } else if (p[1] == '%') {
                // single '%'
                mode = 'c';
                value = '%';
                size = 1;
                break;

            } else if (p[1] == 'c') {
                // char
                mode = 'c';
                value = va_arg(args, int);
                size = 1;
                break;

            } else if (p[1] == 's') {
                // string
                mode = 's';
                const char *s = va_arg(args, const char *);
                value = (uint32_t)s;
                // find size, don't allow overruns
                size = 0;
                while (s[size] && (precision == 0 || size < precision)) {
                    size += 1;
                }
                break;

            } else if (p[1] == 'd' || p[1] == 'i') {
                // signed decimal number
                mode = 'd';
                int32_t d = va_arg(args, int32_t);
                value = (uint32_t)d;
                size = 0;
                if (d < 0) {
                    size += 1;
                    d = -d;
                }
                for (uint32_t t = d; t > 0; t /= 10) {
                    size += 1;
                }
                if (size == 0) {
                    size += 1;
                }
                break;

            } else if (p[1] == 'u') {
                // unsigned decimal number
                mode = 'u';
                value = va_arg(args, uint32_t);
                size = 0;
                for (uint32_t t = value; t > 0; t /= 10) {
                    size += 1;
                }
                if (size == 0) {
                    size += 1;
                }
                break;

            } else if (p[1] >= ' ' && p[1] <= '?') {
                // unknown modifier? skip

            } else {
                // hex or unknown character, terminate

                // make it prettier for pointers
                if (!(p[1] == 'x' || p[1] == 'X')) {
                    zero_justify = true;
                    width = 2*sizeof(void*);
                }

                // hexadecimal number
                mode = 'x';
                value = va_arg(args, uint32_t);
                size = 0;
                for (uint32_t t = value; t > 0; t /= 16) {
                    size += 1;
                }
                if (size == 0) {
                    size += 1;
                }
                break;
            }
        }

        // consume the format
        p += 2;

        // format printing
        if (!left_justify) {
            for (ssize_t i = 0; i < (ssize_t)width-(ssize_t)size; i++) {
                char c = (zero_justify) ? '0' : ' ';
                ssize_t nres = write(ctx, &c, 1);
                if (nres < 0) {
                    return nres;
                }
                res += nres;
            }
        }

        if (mode == 'c') {
            ssize_t nres = write(ctx, &value, 1);
            if (nres < 0) {
                return nres;
            }
            res += nres;
        } else if (mode == 's') {
            ssize_t nres = write(ctx, (const char*)(uintptr_t)value, size);
            if (nres < 0) {
                return nres;
            }
            res += nres;
        } else if (mode == 'x') {
            for (ssize_t i = size-1; i >= 0; i--) {
                uint32_t digit = (value >> (4*i)) & 0xf;

                char c = ((digit >= 10) ? ('a'-10) : '0') + digit;
                ssize_t nres = write(ctx, &c, 1);
                if (nres < 0) {
                    return nres;
                }
                res += nres;
            }
        } else if (mode == 'd' || mode == 'u') {
            ssize_t i = size-1;

            if (mode == 'd' && (int32_t)value < 0) {
                ssize_t nres = write(ctx, "-", 1);
                if (nres < 0) {
                    return nres;
                }
                res += nres;

                value = -value;
                i -= 1;
            }

            for (; i >= 0; i--) {
                uint32_t temp = value;
                for (int j = 0; j < i; j++) {
                    temp /= 10;
                }
                uint32_t digit = temp % 10;

                char c = '0' + digit;
                ssize_t nres = write(ctx, &c, 1);
                if (nres < 0) {
                    return nres;
                }
                res += nres;
            }
        }

        if (left_justify) {
            for (ssize_t i = 0; i < (ssize_t)width-(ssize_t)size; i++) {
                char c = ' ';
                ssize_t nres = write(ctx, &c, 1);
                if (nres < 0) {
                    return nres;
                }
                res += nres;
            }
        }
    }
}

static ssize_t __box_vprintf_write(void *ctx, const void *buf, size_t size) {
    return __box_write((int32_t)ctx, buf, size);
}

__attribute__((used))
ssize_t __wrap_vprintf(const char *format, va_list args) {
    return __box_cbprintf(__box_vprintf_write, (void*)1, format, args);
}

__attribute__((used))
ssize_t __wrap_printf(const char *format, ...) {
    va_list args;
    va_start(args, format);
    ssize_t res = __wrap_vprintf(format, args);
    va_end(args);
    return res;
}

__attribute__((used))
ssize_t __wrap_vfprintf(FILE *f, const char *format, va_list args) {
    int32_t fd = (f == stdout) ? 1 : 2;
    return __box_cbprintf(__box_vprintf_write, (void*)fd, format, args);
}

__attribute__((used))
ssize_t __wrap_fprintf(FILE *f, const char *format, ...) {
    va_list args;
    va_start(args, format);
    ssize_t res = __wrap_vfprintf(f, format, args);
    va_end(args);
    return res;
}

__attribute__((used))
int __wrap_fflush(FILE *f) {
    int32_t fd = (f == stdout) ? 1 : 2;
    return __box_flush(fd);
}

#if defined(__GNUC__)
int _write(int handle, const char *buffer, int size) {
    return __box_write(handle, (const uint8_t*)buffer, size);
}
#endif

//// ISR Vector definitions ////

extern void main(void);

// Reset Handler
__attribute__((naked, noreturn))
int32_t __box_reset_handler(void) {
    // load data
    extern uint32_t __data_init_start;
    extern uint32_t __data_start;
    extern uint32_t __data_end;
    const uint32_t *s = &__data_init_start;
    for (uint32_t *d = &__data_start; d < &__data_end; d++) {
        *d = *s++;
    }

    // zero bss
    extern uint32_t __bss_start;
    extern uint32_t __bss_end;
    for (uint32_t *d = &__bss_start; d < &__bss_end; d++) {
        *d = 0;
    }


    // FPU bringup?
    #if defined(__VFP_FP__) && !defined(__SOFTFP__)
    #define CPACR ((volatile uint32_t*)0xe000ed88)
    *CPACR |= 0x00f00000;
    __asm__ volatile ("dsb");
    __asm__ volatile ("isb");
    #endif

    // init libc
    extern void __libc_init_array(void);
    __libc_init_array();

    // enter main
    main();

    // halt if main exits
    while (1) {
        __asm__ volatile ("wfi");
    }
}

//// Default handlers ////

__attribute__((naked, noreturn))
void __box_nmi_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_hardfault_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_memmanage_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_busfault_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_usagefault_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_svc_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_debugmon_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_pendsv_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_systick_handler(void) {
    while (1) {}
}

__attribute__((naked, noreturn))
void __box_default_handler(void) {
    while (1) {}
}



extern uint32_t __stack_end;

//// ISR Vector ////

__attribute__((used, section(".isr_vector")))
const uint32_t __isr_vector[256] = {
    (uint32_t)&__stack_end,
    (uint32_t)&__box_reset_handler,
    // Exception handlers
    (uint32_t)__box_nmi_handler,
    (uint32_t)__box_hardfault_handler,
    (uint32_t)__box_memmanage_handler,
    (uint32_t)__box_busfault_handler,
    (uint32_t)__box_usagefault_handler,
    (uint32_t)0,
    (uint32_t)0,
    (uint32_t)0,
    (uint32_t)0,
    (uint32_t)__box_svc_handler,
    (uint32_t)__box_debugmon_handler,
    (uint32_t)0,
    (uint32_t)__box_pendsv_handler,
    (uint32_t)__box_systick_handler,
    // External IRQ handlers
    (uint32_t)POWER_CLOCK_IRQHandler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)TIMER0_IRQHandler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
    (uint32_t)__box_default_handler,
};

//// lfsbox loading ////

static int __box_lfsbox_load(void) {
    // default loader does nothing
    return 0;
}

//// lfsbox state ////
bool __box_lfsbox_initialized = false;
uint32_t __box_lfsbox_datasp;
wasm_module_t __box_lfsbox_module;
wasm_module_inst_t __box_lfsbox_module_inst;
wasm_exec_env_t __box_lfsbox_exec_env;
int __box_lfsbox_err;

// default __box_abort implementation
void __box_lfsbox_import___box_lfsbox_abort(
        wasm_exec_env_t env, int err) {
    wasm_module_inst_t module = wasm_runtime_get_module_inst(env);
    int *perr = wasm_runtime_get_user_data(env);
    *perr = err;
    wasm_runtime_set_exception(module, "__box_abort");
}

// redirect __box_lfsbox_write -> __box_write
#define __box_lfsbox_write __box_write

// redirect __box_lfsbox_flush -> __box_flush
#define __box_lfsbox_flush __box_flush

//// lfsbox imports ////

ssize_t __box_lfsbox_import___box_lfsbox_write(wasm_exec_env_t env, int32_t a0, const void *a1, size_t a2) {
    return __box_lfsbox_write(a0, a1, a2);
}

int __box_lfsbox_import___box_lfsbox_flush(wasm_exec_env_t env, int32_t a0) {
    return __box_lfsbox_flush(a0);
}

uint32_t __box_lfsbox_import_bd_block_count(void) {
    return bd_block_count();
}

uint32_t __box_lfsbox_import_bd_block_size(void) {
    return bd_block_size();
}

int __box_lfsbox_import_bd_erase(wasm_exec_env_t env, uint32_t block) {
    return bd_erase(block);
}

int __box_lfsbox_import_bd_prog(wasm_exec_env_t env, uint32_t block, uint32_t off, const void *buffer, size_t size) {
    return bd_prog(block, off, buffer, size);
}

int __box_lfsbox_import_bd_read(wasm_exec_env_t env, uint32_t block, uint32_t off, void *buffer, size_t size) {
    return bd_read(block, off, buffer, size);
}

int __box_lfsbox_import_bd_sync(void) {
    return bd_sync();
}

const NativeSymbol __box_lfsbox_native_symbols[] = {
    {
        "__box_abort",
        __box_lfsbox_import___box_lfsbox_abort,
        "(i)",
        &__box_lfsbox_err,
    },
    {
        "__box_write",
        __box_lfsbox_import___box_lfsbox_write,
        "(i*i)i",
        NULL,
    },
    {
        "__box_flush",
        __box_lfsbox_import___box_lfsbox_flush,
        "(i)i",
        NULL,
    },
    {
        "bd_block_count",
        __box_lfsbox_import_bd_block_count,
        "()i",
        NULL,
    },
    {
        "bd_block_size",
        __box_lfsbox_import_bd_block_size,
        "()i",
        NULL,
    },
    {
        "bd_erase",
        __box_lfsbox_import_bd_erase,
        "(i)i",
        NULL,
    },
    {
        "bd_prog",
        __box_lfsbox_import_bd_prog,
        "(ii*i)i",
        NULL,
    },
    {
        "bd_read",
        __box_lfsbox_import_bd_read,
        "(ii*i)i",
        NULL,
    },
    {
        "bd_sync",
        __box_lfsbox_import_bd_sync,
        "()i",
        NULL,
    },
};

//// lfsbox exports ////

int lfsbox_file_close(int32_t fd) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_file_close",
        "(i)i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*1];
    *(int32_t*)&frame[4*0] = fd;
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        1,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int*)&frame[4*0];
}

int32_t lfsbox_file_open(const char *path, uint32_t flags) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_file_open",
        "(*i)i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*2];
    *(int32_t*)&frame[4*0] = wasm_runtime_addr_native_to_app(
        __box_lfsbox_module_inst,
        (void*)path);
    *(uint32_t*)&frame[4*1] = flags;
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        2,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int32_t*)&frame[4*0];
}

ssize_t lfsbox_file_read(int32_t fd, void *buffer, size_t size) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_file_read",
        "(i*i)i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*3];
    *(int32_t*)&frame[4*0] = fd;
    *(int32_t*)&frame[4*1] = wasm_runtime_addr_native_to_app(
        __box_lfsbox_module_inst,
        (void*)buffer);
    *(size_t*)&frame[4*2] = size;
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        3,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(ssize_t*)&frame[4*0];
}

int32_t lfsbox_file_seek(int32_t fd, int32_t off, uint32_t whence) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_file_seek",
        "(iii)i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*3];
    *(int32_t*)&frame[4*0] = fd;
    *(int32_t*)&frame[4*1] = off;
    *(uint32_t*)&frame[4*2] = whence;
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        3,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int32_t*)&frame[4*0];
}

ssize_t lfsbox_file_write(int32_t fd, const void *buffer, size_t size) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_file_write",
        "(i*i)i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*3];
    *(int32_t*)&frame[4*0] = fd;
    *(int32_t*)&frame[4*1] = wasm_runtime_addr_native_to_app(
        __box_lfsbox_module_inst,
        (void*)buffer);
    *(size_t*)&frame[4*2] = size;
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        3,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(ssize_t*)&frame[4*0];
}

int lfsbox_format(void) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_format",
        "()i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*1];
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        0,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int*)&frame[4*0];
}

int lfsbox_mount(void) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_mount",
        "()i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*1];
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        0,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int*)&frame[4*0];
}

int lfsbox_rename(const char *oldpath, const char *newpath) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_rename",
        "(**)i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*2];
    *(int32_t*)&frame[4*0] = wasm_runtime_addr_native_to_app(
        __box_lfsbox_module_inst,
        (void*)oldpath);
    *(int32_t*)&frame[4*1] = wasm_runtime_addr_native_to_app(
        __box_lfsbox_module_inst,
        (void*)newpath);
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        2,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int*)&frame[4*0];
}

int lfsbox_unmount(void) {
    if (!__box_lfsbox_initialized) {
        int err = __box_lfsbox_init();
        if (err) {
            return err;
        }
    }

    wasm_function_inst_t f;
    f = wasm_runtime_lookup_function(
        __box_lfsbox_module_inst,
        "lfsbox_unmount",
        "()i");
    if (!f) {
        return -ENOEXEC;
    }

    __box_lfsbox_err = 0;

    __attribute__((aligned(4)))
    uint8_t frame[4*1];
    bool res = wasm_runtime_call_wasm(
        __box_lfsbox_exec_env,
        f,
        0,
        (uint32_t*)frame);
    if (!res) {
        if (__box_lfsbox_err) {
            wasm_runtime_set_exception(
                __box_lfsbox_module_inst,
                NULL);
            return __box_lfsbox_err;
        }
        return -EFAULT;
    }

    return *(int*)&frame[4*0];
}

//// lfsbox init ////

int __box_lfsbox_init(void) {
    int err;
    if (__box_lfsbox_initialized) {
        return 0;
    }

    // load the box if unloaded
    err = __box_lfsbox_load();
    if (err) {
        return err;
    }

    // bring up common runtime
    if (!__box_wamr_runtime_initialized) {
        bool success = wasm_runtime_init();
        if (!success) {
            return -EGENERAL;
        }
        __box_wamr_runtime_initialized = true;
    }

    if (!__box_lfsbox_module) {
        bool success = wasm_runtime_register_natives(
            "env",
            (NativeSymbol*)__box_lfsbox_native_symbols,
            sizeof(__box_lfsbox_native_symbols) / sizeof(NativeSymbol));
        if (!success) {
            return -EGENERAL;
        }
    }

    extern uint32_t __box_lfsbox_image;
    __box_lfsbox_module = wasm_runtime_load(
        (const uint8_t*)(&__box_lfsbox_image + 1),
        __box_lfsbox_image,
        NULL, 0);
    if (!__box_lfsbox_module) {
        return -ENOEXEC;
    }

    __box_lfsbox_module_inst = wasm_runtime_instantiate(
        __box_lfsbox_module,
        4096,
        0,
        NULL, 0);
    if (!__box_lfsbox_module_inst) {
        return -ENOEXEC;
    }

    __box_lfsbox_exec_env = wasm_runtime_create_exec_env(
        __box_lfsbox_module_inst,
        4096);
    if (!__box_lfsbox_exec_env) {
        return -ENOEXEC;
    }

    wasm_runtime_set_user_data(
        __box_lfsbox_exec_env,
        &__box_lfsbox_err);

    // setup data stack
    __box_lfsbox_datasp = 0;

    __box_lfsbox_initialized = true;
    return 0;
}

int __box_lfsbox_clobber(void) {
    if (__box_lfsbox_initialized) {
        wasm_runtime_destroy_exec_env(__box_lfsbox_exec_env);
        wasm_runtime_deinstantiate(__box_lfsbox_module_inst);
        wasm_runtime_unload(__box_lfsbox_module);
    }
    __box_lfsbox_initialized = false;
    return 0;
}

void *__box_lfsbox_push(size_t size) {
    // we maintain a separate stack in the wasm memory space,
    // sharing the stack space of the wasm-side libc
    uint32_t psp = __box_lfsbox_datasp;
    if (psp + size > 32768) {
        return NULL;
    }

    __box_lfsbox_datasp = psp + size;
    return wasm_runtime_addr_app_to_native(
            __box_lfsbox_module_inst, psp);
}

void __box_lfsbox_pop(size_t size) {
    assert(__box_lfsbox_datasp - size >= 0);
    __box_lfsbox_datasp -= size;
}

