from .. import outputs
from ..box import Fn
from .h import HOutput
import io
import textwrap

@outputs.output
class COutput(outputs.HOutput):
    """
    Name of source file to target for building a jumptable.
    """
    __argname__ = "c"
    __arghelp__ = __doc__

    def build(self, box):
        outputs.Output.build(self, box)
        self.printf('////// AUTOGENERATED //////')

        includes = set()
        for include in self.includes:
            includes.add(include.getvalue())
        out = self.decls.insert(0)
        for include in sorted(includes):
            out.print('#include %s' % include)

        for decl in self.decls:
            if 'doc' in decl:
                for line in textwrap.wrap(decl['doc'], width=78-3):
                    self.print('// %s' % line)
            self.print(decl.getvalue().strip())
            self.print()
