from .. import outputs
import io

@outputs.output('sys')
@outputs.output('box')
class JumptableOutput(outputs.Output):
    """
    Name of source file to target for building a jumptable.
    """
    __argname__ = "c_glue"
    __arghelp__ = __doc__

    def __init__(self, sys, box, path):
        self._includes = []
        self._decls = []
        super().__init__(sys, box, path)

    def append_include(self, fmt=None, **kwargs):
        include = fmt % self.mkformat(**kwargs)
        if not include.startswith('"') and not include.startswith('<'):
            include = '"%s"' % include
        if include not in self._includes:
            self._includes.append(include)

    def append_decl(self, fmt=None, **kwargs):
        outf = self.mkfield(**kwargs)
        self._decls.append(outf)
        if fmt is not None:
            outf.write(fmt)
        return outf

    def build(self, outf):
        outf.write('////// AUTOGENERATED //////\n')
        for include in self._includes:
            outf.write('#include %s\n' % include)
        outf.write('\n')
        for decl in self._decls:
            outf.write(decl.getvalue())
            outf.write('\n')
