memory.flash = 'rxp 0x00000000-0x000fffff'
memory.ram   = 'rw 0x20000000-0x2003ffff'
stack = 0x8000
heap = 0x32000

runtime = 'armv7m-sys'
output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk.path = 'Makefile'
output.mk.define.NRF52840_XXAA=1
output.mk.define.NRFX_UARTE_ENABLED=1
output.mk.define.NRFX_UARTE0_ENABLED=1
output.mk.srcs = [
    '.',
    'nrfx/drivers/src',
    'wasm3/source',
]
output.mk.incs = [
    '.',
    'nrfx',
    'cmsis',
    'nrfx/drivers/include',
    'nrfx/mdk',
    'nrfx/templates',
    'wasm3/source',
]

# These are needed for wasm3
# TODO fix upstream?
output.mk.define.PRIi64='"lli"'
output.mk.define.PRIu64='"llu"'
output.mk.c_flags = [
    '-Wno-unused-function',
    '-Wno-unused-variable',
    '-Wno-strict-aliasing',
]

export.__box_write = 'fn(i32, const u8[size], usize size) -> errsize'
import.box_qsort = 'fn(mut u32 buffer[size], usize size) -> err'

[box.qsort]
runtime.runtime = 'wasm3'
runtime.wasm3.data_stack = 0x8000
runtime.wasm3.interp_stack = 0x1000
memory.flash = 'rxp 0x8000'

output.wasm_h = 'bb.h'
output.wasm_c = 'bb.c'
output.mk.path = 'Makefile'
output.mk.wasi_sdk = '../wasi-sdk'
output.mk.wabt = '../wabt'

export.box_qsort = 'fn(mut u32 buffer[size], usize size) -> err'
