name = 'boxrust'
runtime = 'armv7m_mpu'
memory.flash = 'rxp 0x8000'
memory.ram = 'rw 0x2000'
stack = 0x800
heap = 0x800

output.ld = 'bb/src/bb.ld'
output.c = 'bb/src/bb.c'
output.rs.path = 'bb/src/lib.rs'
output.rs.no_runtime_logic = true
output.mk.path = 'Makefile'
output.mk.srcs = ['.', 'bb/src']

export.boxrust_add2= 'fn(i32, i32) -> err32'
export.boxrust_hello = 'fn() -> err'

export.boxrust_fib_alloc = 'fn(size: usize) -> nullable mut u8*'
export.boxrust_fib_next = 'fn(next: mut u32*, a: u32, b: u32) -> err'
export.boxrust_fib = '''
    fn(buffer: mut u32[size], size: usize, a: u32, b: u32) -> err
    '''

export.boxrust_qsort_alloc = 'fn(size: usize) -> nullable mut u8*'
export.boxrust_qsort_partition = '''
    fn(buffer: mut u32[size], size: usize, pivot: u32) -> errsize
    '''
export.boxrust_qsort = 'fn(buffer: mut u32[size], size: usize) -> err'

[super.sys]
memory.flash = 'rxp 0x00000000-0x000fffff'
memory.ram   = 'rw 0x20000000-0x2003ffff'
stack = 0x800
heap = 0x800

runtime = 'armv7m_sys'
output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk.path = 'Makefile'
output.mk.define.NRF52840_XXAA=1
output.mk.define.NRFX_UARTE_ENABLED=1
output.mk.define.NRFX_UARTE0_ENABLED=1
output.mk.srcs = [
    '.',
    'nrfx/drivers/src',
]
output.mk.incs = [
    '.',
    'nrfx',
    'cmsis',
    'nrfx/drivers/include',
    'nrfx/mdk',
    'nrfx/templates'
]

export.__box_write = '''
    fn(i32, const u8*, usize) -> errsize
    '''

import.boxrust_add2= 'fn(i32, i32) -> err32'
import.boxrust_hello = 'fn() -> err'

import.boxrust_fib_alloc = 'fn(size: usize) -> nullable mut u8*'
import.boxrust_fib_next = 'fn(next: mut u32*, a: u32, b: u32) -> err'
import.boxrust_fib = '''
    fn(buffer: mut u32[size], size: usize, a: u32, b: u32) -> err
    '''

import.boxrust_qsort_alloc = 'fn(size: usize) -> nullable mut u8*'
import.boxrust_qsort_partition = '''
    fn(buffer: mut u32[size], size: usize, pivot: u32) -> errsize
    '''
import.boxrust_qsort = 'fn(buffer: mut u32[size], size: usize) -> err'
