memory.flash = 'rxp 0x00000000-0x000fffff'
memory.ram   = 'rw 0x20000000-0x2003ffff'
stack = 0x800
heap = 0x800

runtime = 'armv7m-sys'
output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk.path = 'Makefile'
output.mk.define.NRF52840_XXAA=1
output.mk.define.NRFX_UARTE_ENABLED=1
output.mk.define.NRFX_UARTE0_ENABLED=1
output.mk.srcs = [
    '.',
    'nrfx/drivers/src',
]
output.mk.incs = [
    '.',
    'nrfx',
    'cmsis',
    'nrfx/drivers/include',
    'nrfx/mdk',
    'nrfx/templates'
]

export.__box_write = 'fn(i32, const u8*, usize) -> errsize'

import.box1_add2  = 'fn(i32, i32) -> err32'
import.box1_hello = 'fn() -> err'
import.box1_badassert = 'fn() -> err'
import.box1_badread   = 'fn() -> err'
import.box1_badwrite  = 'fn() -> err'
import.box1_overflow  = 'fn() -> err'

[box.box1]
runtime = 'armv7m-mpu'
memory.flash = 'rxp 0x2000'
memory.ram = 'rw 0x2000'
stack = 0x800
heap = 0x800

output.ld = 'bb.ld'
output.h = 'bb.h'
output.c = 'bb.c'
output.mk = 'Makefile'

export.box1_add2 = 'fn(i32, i32) -> err32'
export.box1_hello = 'fn() -> err'
export.box1_badassert = 'fn() -> err'
export.box1_badread   = 'fn() -> err'
export.box1_badwrite  = 'fn() -> err'
export.box1_overflow  = 'fn() -> err'
